IncompNS += ins_interface.o \
            ins_init.o \
            ins_indicators.o \
            ins_divergence.o \
            ins_diffusion_vardens.o \
            ins_corrector.o \
            ins_setupPoissonRhs.o \
            ins_computeDtLocal.o \
            ins_extrasInterface.o \
            ins_velToCenter.o \
            ins_omgToCenter.o
