# FLASH makefile definitions for Linux box (GCC compiler)

#----------------------------------------------------------------------------
# Set the HDF5/MPI library paths -- these need to be updated for your system
#----------------------------------------------------------------------------

MPI_PATH   = ${MPICH_DIR}
HDF5_PATH  = ${HDF5_DIR}
HYPRE_PATH = ${HYPRE_DIR}
CUDA_PATH  = ${CUDA_DIR}
MAGMA_PATH = ${MAGMA_DIR}
AMREX_PATH = ${AMREX_DIR}/etacar_${NDIM}d_gnu

ZLIB_PATH  =

PAPI_PATH  = ${PAPI_DIR}
PAPI_FLAGS =

NCMPI_PATH = ${PARALLEL_NETCDF_DIR}
MPE_PATH   =

LAPACK_PATH=/usr/lib/x86_64-linux-gnu/openblas

#----------------------------------------------------------------------------
# Compiler and linker commands
#
#   Use the MPICH wrappers around the compilers -- these will automatically
#   load the proper libraries and include files.  Version of MPICH prior
#   to 1.2.2 (?) do not recognize .F90 as a valid Fortran file extension.
#   You need to edit mpif90 and add .F90 to the test of filename extensions,
#   or upgrade your MPICH.
#----------------------------------------------------------------------------

FCOMP   = mpif90
CCOMP   = mpicc
CPPCOMP = mpicxx
LINK    = mpif90 -std=c++11

# pre-processor flag
MDEFS =
PP    = -D

#----------------------------------------------------------------------------
# Compilation flags
#
#  Three sets of compilation/linking flags are defined: one for optimized
#  code, one for testing, and one for debugging.  The default is to use the
#  _OPT version.  Specifying -debug to setup will pick the _DEBUG version,
#  these should enable bounds checking.  Specifying _TEST is used for
#  flash_test, and is set for quick code generation, and (sometimes)
#  profiling.  The Makefile generated by setup will assign the generic token
#  (ex. FFLAGS) to the proper set of flags (ex. FFLAGS_OPT).
#----------------------------------------------------------------------------

OPENMP = -fopenmp

FFLAGS_AMREX = -I${AMREX_PATH}/include
FFLAGS_HDF5  = -I${HDF5_PATH}/include ${MDEFS}${PP}H5_USE_18_API
FFLAGS_NCMPI = -I${NCMPI_PATH}/include
FFLAGS_HYPRE = -I${HYPRE_PATH}/include ${FFLAGS_LAPACK}
FFLAGS_CUDA  = -I${CUDA_PATH}/include
FFLAGS_MAGMA = -I${MAGMA_PATH}/include
FFLAGS_OACC  = -fopenacc
FFLAGS_LAPACK= -I${LAPACK_PATH}

OPT_FLAGS    = -g -Ofast -funroll-loops -fprefetch-loop-arrays
TEST_FLAGS   = -g -O3
DEBUG_FLAGS  = -g -Og -ggdb -fstack-check -fstack-protector-all -ftrapv -fexceptions

FFLAGS_OPT   = -c ${OPT_FLAGS}
FFLAGS_TEST  = -c ${TEST_FLAGS}
FFLAGS_DEBUG = -c ${DEBUG_FLAGS} -fcheck=bounds,do,mem,pointer -ffpe-trap=invalid,zero,overflow -fbacktrace

F90FLAGS     = -fdefault-real-8 -fdefault-double-8 -fimplicit-none -ffree-line-length-none -cpp
f90FLAGS     = ${F90FLAGS}
F77FLAGS     = -fdefault-real-8 -fdefault-double-8 -fimplicit-none -cpp
f77FLAGS     = ${F77FLAGS}

CFLAGS_AMREX = -I${AMREX_PATH}/include
CFLAGS_HDF5  = -I$(HDF5_PATH)/include ${PP}H5_USE_18_API
CFLAGS_NCMPI = -I$(NCMPI_PATH)/include
CFLAGS_HYPRE = -I${HYPRE_PATH}/include ${CFLAGS_LAPACK}
CFLAGS_CUDA  = -I${CUDA_PATH}/include
CFLAGS_MAGMA = -I${MAGMA_PATH}/include
CFLAGS_OACC  = -fopenacc
CFLAGS_LAPACK= -I${LAPACK_PATH}

CFLAGS_OPT   = -c ${OPT_FLAGS}
CFLAGS_TEST  = -c ${TEST_FLAGS}
CFLAGS_DEBUG = -c ${DEBUG_FLAGS}

CU_FLAGS     = -c -g -O2 -m64

.SUFFIXES: .o .c .f .F .h .fh .F90 .f90 .cu

#----------------------------------------------------------------------------
# Linker flags
#----------------------------------------------------------------------------
LFLAGS_OPT   = ${OPT_FLAGS} -o
LFLAGS_TEST  = ${TEST_FLAGS} -o
LFLAGS_DEBUG = ${DEBUG_FLAGS} -o

#----------------------------------------------------------------------------
# Library specific linking
#
#  If a FLASH module has a 'LIBRARY xxx' line in its Config file, we need to
#  create a macro in this Makefile.h for LIB_xxx, which will be added to the
#  link line when FLASH is built.  This allows us to switch between different
#  (incompatible) libraries.  We also create a _OPT, _DEBUG, and _TEST
#  library macro to add any performance-minded libraries (like fast math),
#  depending on how FLASH was setup.
#----------------------------------------------------------------------------

LIB_MPI   =

LIB_AMREX = -L${AMREX_PATH}/lib -lamrex -lstdc++
LIB_STDCXX= -lstdc++

LIB_HDF5  = -L${HDF5_PATH}/lib -lhdf5_fortran -lhdf5
LIB_NCMPI = -L${NCMPI_PATH}/lib -lpnetcdf
LIB_LAPACK= -L${LAPACK_PATH} -llapack -lblas
LIB_HYPRE = -L${HYPRE_PATH}/lib -lHYPRE ${LIB_LAPACK}
LIB_CUDA  = -L${CUDA_PATH}/lib64 -lcublas -lcudart -lcuda
LIB_MAGMA = -L$(MAGMA_PATH)/lib -lmagma -Wl,-rpath,$(MAGMA_PATH)/lib
LIB_OACC  =

LIB_OPT   =
LIB_DEBUG =
LIB_TEST  =

#----------------------------------------------------------------------------
# Additional machine-dependent object files
#
#  Add any machine specific files here -- they will be compiled and linked
#  when FLASH is built.
#----------------------------------------------------------------------------

MACHOBJ =

#----------------------------------------------------------------------------
# Additional commands
#----------------------------------------------------------------------------

MV = mv -f
AR = ar -r
RM = rm -f
CD = cd
RL = ranlib
ECHO = echo
AWK = awk
CAT = cat
