# This test is actually not a DeleptonizationWave, but a CCSN simulation
# TODO: Create a different Simulation directory
["Comparison/DeleptonizationWave/PseudoUG/1dSph/Paramesh"]
    setupOptions = "-auto -1d +spherical -nxb=16 -maxblocks=100 +pm4dev +hdf5 +uhd +thornado nE=5 nSpecies=2 nNodes=2 nMoments=4 momentClosure=MINERBO thornadoSolver=EMAB +weaklib"
    parfiles = ["test_sph_1d_mcs.par"]
    #restartParfiles = ["test_sph_1d_mcs_restart.par"]
    transfers = ["object/Chimera_S25+100ms_r_Boltz",
                 "object/Chimera_S25+100ms_h"]
    errTol = 1.0e-9

#["Comparison/StreamingSineWave/PseudoUG/2d/Paramesh"]
#    setupOptions = "-auto -2d +cartesian -nxb=16 -nyb=16 -maxblocks=400 +pm4dev +hdf5 +uhd +thornado nE=16 nSpecies=2 nNodes=2 nMoments=4 momentClosure=MAXIMUM_ENTROPY_CB thornadoSolver=FIXED_POINT_NESTED_AA +weaklib"
#    parfiles = ["test_car_2d_mcs.par"]
#    #restartParfiles = ["test_car_2d_mcs_restart.par"]
#    transfers = ["object/wl-EOS-SFHo-15-25-50-noBCK.h5"]
#    errTol = 1.0e-9
#
#["Comparison/StreamingSineWave/PseudoUG/3d/Paramesh"]
#    setupOptions = "-auto -3d +cartesian -nxb=16 -nyb=16 -nzb=16 -maxblocks=100 +pm4dev +hdf5 +uhd +thornado nE=8 nSpecies=2 nNodes=2 nMoments=4 momentClosure=MAXIMUM_ENTROPY_CB thornadoSolver=FIXED_POINT_NESTED_AA +weaklib"
#    parfiles = ["test_car_3d_mcs.par"]
#    #restartParfiles = ["test_car_3d_mcs_restart.par"]
#    transfers = ["object/wl-EOS-SFHo-15-25-50-noBCK.h5"]
#    errTol = 1.0e-8
