Hydro += Hydro_interface.o Hydro.o Hydro_init.o Hydro_sendOutputData.o Hydro_computeDt.o Hydro_shockStrength.o Hydro_finalize.o \
         Hydro_consolidateCFL.o\
         Hydro_gravPotIsAlreadyUpdated.o\
         Hydro_mapBcType.o
Hydro += Hydro_prepareBuffers.o Hydro_freeBuffers.o
Hydro += Hydro_molExplicitRHS.o \
	     Hydro_molImplicitRHS.o \
	     Hydro_molFastRHS.o \
	     Hydro_molImplicitUpdate.o \
	     Hydro_molPostUpdate.o \
	     Hydro_molPostFastUpdate.o \
	     Hydro_molPreEvolve.o \
	     Hydro_molPostTimeStep.o \
	     Hydro_molPostRegrid.o
