# Makefile for Weaklib equation of state

Eos += eos_wlData.o \
       eos_weaklibInit.o \
       eos_weaklib_inter.o \
       eos_weaklib.o \
       eos_wlInterface.o \
       eos_wlEnerShift.o \
       eos_wlOneZone.o \
       eos_wlDetectBounce.o \
       eos_wlPotentials.o

