# Top level configuration file for Rising Bubble problem

[Simulation]
  sim_bubbleRadius = 0.5
  sim_lengthScaleMeters = 0.5
  sim_timeScaleSeconds = 0.714

[Logfile]
  run_comment = "Rising Bubble problem"
  log_file = "INS_Rising_Bubble.log"

[Grid]
  geometry = "cartesian"
  xmin = -1.0
  xmax = 1.0
  ymin = -1.0
  ymax = 3.0
  xl_boundary_type = "slip_ins"
  xr_boundary_type = "slip_ins"
  yl_boundary_type = "noslip_ins"
  yr_boundary_type = "noslip_ins"
  zl_boundary_type = "noslip_ins"
  zr_boundary_type = "noslip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1e-13
  gr_amrexMG_max_iter = 200
  nblockx = 5
  nblocky = 10
  nrefs = 10000
  lrefine_min = 1
  lrefine_max = 1

[Driver]
  tstep_change_factor = 1.0
  nend = 10000000
  tmax = 5
  dtinit = 5e-5
  dtmax = 5e-5

[IncompNS]
  ins_cflFlg = 0
  ins_cfl = 0.05
  ins_sigma = 0.05
  ins_pressureCorrect = false
  ins_intSchm = 1 # Euler explicit
  ins_advSchm = 105 # WENO5
  ins_invReynolds = 0.0285
  ins_gravY = -1.0
  ins_dtSpec = 5e-5

[Multiphase]
  mph_lsIt = 2
  mph_rhoGas = 0.001
  mph_muGas = 0.01
  mph_iPropSmear = 1.0
  mph_invWeber = 0.008

[IO]
  basenm = "INS_Rising_Bubble_"
  checkpointFileIntervalTime = 1.0
  checkpointFileIntervalStep = 0
  plotFileIntervalTime = 0.1
  plotFileIntervalStep = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "visc"
  plot_var_6 = "rhoc"
  plot_var_7 = "dust"
