Heater += htr_interface.o \
          htr_annInterface.o \
          htr_read.o \
          htr_lsReInitBlk.o \
          htr_checkSitesBlk.o \
          htr_annBuildTree.o \
          htr_annSearchTree.o \
