name: checks

on:
  pull_request:
    branches: 
      - main

# Container jobs
jobs:
  pull-request-from-staged:
    name: "pull-request-from-staged"
    runs-on: ubuntu-latest
    steps:
    - name: Check if head branch is staged
      if:  ${{ github.event.pull_request.head.ref == 'staged' }}
      run: |
           echo "Pull request is from staged."
           exit 0
    - name: Check if head branch is not staged
      if: ${{ github.event.pull_request.head.ref != 'staged' }}
      run: |
           echo "Pull request is not from staged."
           exit 1
