# Name of the github-docker workflow
name: Sedov

# Perform container on pull request
on:
  workflow_dispatch:

  pull_request:
    branches: 
      - Fluid-Dynamics
    paths-ignore:
      - '**.md'
      - 'sites/**'
      - 'docs/**'
      - 'LICENSE'
    
# Container jobs
jobs:
  Sedov:
    name: "Sedov"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: akashdhruv/Maple/.github/actions/maple@main
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Run container
      run: |   
          python3 container/Sedov/Sedov.py
