!> @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

!> @ingroup OrchestrationMilhoja
!!
!! @brief Data module for Orchestration unit
!!
!! @details
!! This module contains runtime parameters required for each Orchestraion invocation
!! during the TimeAdvance. This module is intended to use only inside of TimeAdvance
!! generated by RecipeCompilers
module Orchestration_data

    implicit none
    save

    integer :: or_nThreads_1, &
               or_nThreads_2, &
               or_nThreads_3, &
               or_nThreads_4, &
               or_nThreads_5

    integer :: or_nTilesPerPacket_1, &
               or_nTilesPerPacket_2, &
               or_nTilesPerPacket_3, &
               or_nTilesPerPacket_4, &
               or_nTilesPerPacket_5


end module Orchestration_data

