#	Makefile for Grid/GridSolvers/HYPRE

Grid += gr_hypreData.o gr_hypreLocalInterface.o gr_hypreF90CAdapters.o \
	gr_hypre_fortran_message.o gr_hypreApplyBcToFace.o

Grid +=  gr_hypreComputeB.o gr_hypreSetupSolver.o gr_hypreDestroySolver.o  \
         gr_hypreDestroyGrid.o gr_hypreSetupGrid.o gr_hypreCreateMatrix.o \
         gr_hypreSolve.o gr_hypreUpdateSoln.o gr_hypreSetIniGuess.o \
         gr_hypreGridStatus.o gr_hypreAddGraph.o gr_hypreLevel.o
