HeatAD += HeatAD_interface.o \
          HeatAD_init.o \
          HeatAD_finalize.o \
          HeatAD_solve.o \
          HeatAD_advection.o \
          HeatAD_diffusion.o \
          HeatAD_indicators.o \
          HeatAD_getGridVar.o \
          HeatAD_getScalarProp.o \
          HeatAD_reInitGridVars.o
