!!****if* source/physics/sourceTerms/Burn/BurnMain/nuclearBurn/Aprox19/bn_mapNetworkToSpecies
!! NOTICE
!!  Copyright 2022 UChicago Argonne, LLC and contributors
!!
!!  Licensed under the Apache License, Version 2.0 (the "License");
!!  you may not use this file except in compliance with the License.
!!
!!  Unless required by applicable law or agreed to in writing, software
!!  distributed under the License is distributed on an "AS IS" BASIS,
!!  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!!  See the License for the specific language governing permissions and
!!  limitations under the License.
!!
!! NAME
!!
!!  bn_mapNetworkToSpecies
!!
!! SYNOPSIS
!!
!!  bn_mapNetworkToSpecies(integer, intent(IN)  :: networkIn,
!!                         integer, intent(OUT) :: specieOut)
!!
!! DESCRIPTION
!!
!!  Maps network indices required by Aprox19 to species generated by Simulation.h
!!
!!
!! ARGUMENTS
!!
!!  networkIn -- integer index of the network as defined in Aprox19 routines
!!  specieOut -- integer corresponding to the same specie in Simulation.h
!!
!!***

subroutine bn_mapNetworkToSpecies(networkIn,specieOut)

  
  use Driver_interface, ONLY: Driver_abort
  use Logfile_interface, ONLY: Logfile_stampMessage

  implicit none

#include "Simulation.h"

  integer, intent(IN)  ::   networkIn
  integer, intent(OUT) :: specieOut

  !! Local variable for error diagnostics
  character*256 :: internalFile
  

  select case (networkIn)
  case (1)
     specieOut = H1_SPEC
  case (2)
     specieOut = HE3_SPEC
  case (3)
     specieOut = HE4_SPEC
  case (4)
     specieOut = C12_SPEC
  case (5)
     specieOut = N14_SPEC
  case (6)
     specieOut = O16_SPEC
  case (7)
     specieOut = NE20_SPEC
  case (8)
     specieOut = MG24_SPEC
  case (9)
     specieOut = SI28_SPEC
  case (10)
     specieOut = S32_SPEC
  case (11)
     specieOut = AR36_SPEC
  case (12)
     specieOut = CA40_SPEC
  case (13)
     specieOut = TI44_SPEC
  case (14)
     specieOut = CR48_SPEC
  case (15)
     specieOut = FE52_SPEC
  case (16)
     specieOut = FE54_SPEC
  case (17)
     specieOut = NI56_SPEC
  case (18)
     specieOut = NEUT_SPEC
  case (19)
     specieOut = PROT_SPEC
  case default
     !! Abort
     
     call Logfile_stampMessage('ERROR in bn_mapNetworkToSpecies')
     write(internalFile,*)&
          '[bn_mapNetworkToSpecies] Index ',networkIn,' cannot be mapped to a Simulation.h species'
     call Logfile_stampMessage(internalFile)
     call Driver_abort(internalFile)
  end select


  return
end subroutine bn_mapNetworkToSpecies
