Orchestration += Orchestration_init.o \
		         Orchestration_finalize.o \
		         Orchestration_interfaceTypeDecl.o \
		         Orchestration_interface.o \
		         Orchestration_checkInternalError.o \
		         Orchestration_setupPipelineForCpuTasks.o \
		         Orchestration_setupPipelineForGpuTasks.o \
		         Orchestration_setupPipelineForCpuGpuTasks.o \
		         Orchestration_setupPipelineForExtGpuTasks.o \
		         Orchestration_pushTileToCpuPipeline.o \
		         Orchestration_pushTileToGpuPipeline.o \
		         Orchestration_pushTileToCpuGpuPipeline.o \
		         Orchestration_pushTileToCpuGpuSplitPipeline.o \
		         Orchestration_pushTileToExtGpuPipeline.o \
		         Orchestration_teardownPipelineForCpuTasks.o \
		         Orchestration_teardownPipelineForGpuTasks.o \
		         Orchestration_teardownPipelineForCpuGpuTasks.o \
		         Orchestration_teardownPipelineForCpuGpuSplitTasks.o \
		         Orchestration_teardownPipelineForExtGpuTasks.o \
		         Orchestration_executeTasks_Cpu.o \
		         Orchestration_executeTasks_Gpu.o \
		         Orchestration_executeTasks_CpuGpu.o \
		         Orchestration_executeTasks_CpuGpuSplit.o \
		         Orchestration_executeTasks_extGpu.o

