!> @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

!> @ingroup OrchestrationMilhoja
!! @stubref{Orchestration_executeTasks_extGpu}
!!
!! @brief Stub implementation of Orchestration_executeTasks_extGpu
!!
!! @details
!! Use the runtime to execute the given task function using the Extended CPU thread
!! team configuration.  Upon termination, the task functions will have been applied
!! by CPU and "GPU" teams to all leaf blocks using the given number of threads.
!! The order in which the task functions are applied to blocks should not be relied
!! upon, except that, for a given tile, the "GPU" action is always applied before
!! the "Post-GPU" action is applied by the CPU team.
!!
!! @note
!! An actual, non-stub implementation of this interface is only available if (1)
!! Flash-X is linked with a Milhoja library that was configured to support datapackets
!! and wrapped tiles, (2) the linked Milhoja library was also configured to
!! support execute-style orchestration calls, and (3) Flash-X was configured
!! with a "Milhoja" setup variable that requests such an implementation, such as
!! Milhoja="...,CUDA,..." or Milhoja="...,HOSTMEM,..." - this condition is also
!! known as "specifying a GPU-compatible runtime backend".
!! The only existing implementation additionally requires that Flash-X uses the
!! "Milhoja" Grid implementation and that the Milhoja library fully provides the
!! necessary grid backend; currently known variants of the Milhoja library do
!! this by using the AMReX library as their grid backend.
!!
!! @param MH_taskFunction       The task function to be executed by the "GPU"
!!                              thread team.  It is assumed that this function
!!                              was written to launch kernels on GPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use gpu_tf_hydro_mod,ONLY: gpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param MH_postTaskFunction   The task function to be executed by the "Post-GPU"
!!                              thread team.  It is assumed that this function
!!                              was written to execute on CPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use cpu_tf_hydro_mod,ONLY: cpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param nDistributorThreads   The number of distributor threads to use
!! @param nThreads              The number of threads to activate in the teams
!!                              that apply the task functions.
!! @param nTilesPerPacket       The maximum number of tiles allowed in each
!!                              datapacket.
!! @param MH_packet_Cptr        Pointer to a prototype datapacket, from which
!!                              the orchestration runtime will generate new
!!                              datapackets.
!!                              Prototype datapackets are created by calling
!!                              a function like, for example,
!!                              instantiate_gpu_tf_hydro_packet_C in the case
!!                              of orchestrating work for a Hydro operation.
!! @param MH_postProto_Cptr     Pointer to a tile wrapper object, from which
!!                              the orchestration runtime will generate new
!!                              tile wrapper objects.
!!                              Prototype tile wrappers are created by calling
!!                              a function like, for example,
!!                              instantiate_cpu_tf_hydro_wrapper_c in the case
!!                              of orchestrating work for a Hydro operation.
subroutine Orchestration_executeTasks_extGpu(MH_taskFunction,     &
                                          MH_postTaskFunction,     &
                                          nDistributorThreads, &
                                          nThreads,            &
                                          nTilesPerPacket,     &
                                          MH_packet_Cptr,     &
                                          MH_postProto_Cptr)
    use iso_c_binding, ONLY : C_PTR
    use Orchestration_interfaceTypeDecl, ONLY : milhoja_runtime_taskFunction
    implicit none

    procedure(milhoja_runtime_taskFunction)            :: MH_taskFunction
    procedure(milhoja_runtime_taskFunction)            :: MH_postTaskFunction
    integer,                                intent(IN) :: nDistributorThreads
    integer,                                intent(IN) :: nThreads
    integer,                                intent(IN) :: nTilesPerPacket
    type(C_PTR),                            intent(IN) :: MH_packet_CPtr
    type(C_PTR),                            intent(IN) :: MH_postProto_CPtr

end subroutine Orchestration_executeTasks_extGpu

