!! @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

!> @ingroup OrchestrationMilhoja
!! @stubref{Orchestration_setupPipelineForCpuGpuTasks}
!!
!! @brief Stub implementation of Orchestration_setupPipelineForCpuGpuTasks
!!
!! @details
!! Set up the orchestration runtime so that it is ready to execute the given
!! task function with either the CPU/GPU or the Split CPU/GPU thread team
!! configuration.  Upon successful completion of the setup, the orchestration
!! runtime will be ready to accept data items (tiles) pushed to it for
!! execution with Orchestration_pushTileToGpuGpuPipeline or
!! Orchestration_pushTileToGpuGpuSplitPipeline calls.
!! To end the cycle, a call to Orchestration_setupPipelineForCpuGpuTasks has
!! to be matched with an Orchestration_teardownPipelineForCpuGpuTasks or an
!! Orchestration_teardownPipelineForCpuGpuSplitTasks call.
!!
!! @note
!! An actual, non-stub implementation of this interface is only available if
!! (1) Flash-X is linked with a Milhoja library that was configured to support
!! datapackets and wrapped tiles and (2) Flash-X was configured with a
!! "Milhoja" setup variable that requests such an implementation, such as
!! Milhoja="...,CUDA,..." or Milhoja="...,HOSTMEM,...". The condition (2) is
!! also known as "specifying a GPU-compatible runtime backend".
!!
!! @note
!! The MH_pktTaskFunction and MH_tileTaskFunction should generally refer to
!! implementations of different numerical functionality when a CPU/GPU
!! thread team configuration is used. Moreover, the sets (or ranges) of
!! output variables (e.g., of UNK variables) that are updated by the two
!! task functions should be distinct.
!! That is because the input tiles will get processed both by the tile task
!! function on a CPU as well as by the packet task function (as part of a
!! datapacket) "on a GPU", with subsequent combination of the results for
!! each tile.
!! The validity of any user algorithm should not depend on the order in which
!! the two task functions get applied to a tile.
!!
!! @note
!! The MH_pktTaskFunction and MH_tileTaskFunction should generally refer to
!! implementations of "the same" numerical functionality when a CPU/GPU Split
!! thread team configuration is used. That is because some tiles will get
!! processed by the tile task function on a CPU, other tiles by the packet
!! task function (as part of a datapacket) "on a GPU", and the validity of
!! any user algorithm should not depend on which gets processed where.
!!
!! @param MH_pktTaskFunction    The task function to be executed by the "GPU"
!!                              thread team.  It is assumed that this function
!!                              was written to launch kernels on GPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use gpu_tf_hydro_mod,ONLY: gpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param MH_tileTaskFunction    The task function to be executed by the "CPU"
!!                              thread team.  It is assumed that this function
!!                              was written to execute kernels on CPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use cpu_tf_hydro_mod,ONLY: cpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param nThreads              The number of threads to activate in the teams
!!                              that applies the task functions.
!! @param nTilesPerPacket       The maximum number of tiles allowed in each
!!                              datapacket.
!! @param MH_pktProto_Cptr      Pointer to a prototype datapacket, from which
!!                              the orchestration runtime will generate new
!!                              datapackets.
!!                              Prototype datapackets are created by calling
!!                              a function like, for example,
!!                              instantiate_gpu_tf_hydro_packet_C in the case
!!                              of orchestrating work for a Hydro operation.
!! @param nTilesPerCpuTurn      The presence of this optional argument
!!                              determines whether a CPU/GPU or a Split
!!                              CPU/GPU thread team configuration is
!!                              requested. If nTilesPerCpuTurn is present, it
!!                              should be a positive integer; it determines,
!!                              for the Split CPU/GPU bundle, how many tiles
!!                              should be enqueued separately to the CPU team
!!                              before beginning to fill the next datapacket
!!                              (with the next nTilesPerPacket tile that are
!!                              pushed) for enqueueing to the GPU team.
subroutine Orchestration_setupPipelineForCpuGpuTasks(MH_pktTaskFunction, &
                                          MH_tileTaskFunction,     &
                                          nThreads,            &
                                          nTilesPerPacket,     &
                                          MH_pktProto_Cptr,    &
                                          nTilesPerCpuTurn)
    use iso_c_binding, ONLY : C_PTR

    use Orchestration_interfaceTypeDecl, ONLY : milhoja_runtime_taskFunction

    implicit none

    procedure(milhoja_runtime_taskFunction)            :: MH_pktTaskFunction
    procedure(milhoja_runtime_taskFunction)            :: MH_tileTaskFunction
    integer,                                intent(IN) :: nThreads
    integer,                                intent(IN) :: nTilesPerPacket
    type(C_PTR),                            intent(IN) :: MH_pktProto_CPtr
    integer,OPTIONAL,                       intent(IN) :: nTilesPerCpuTurn
end subroutine Orchestration_setupPipelineForCpuGpuTasks

