!! @copyright Copyright 2024 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!! Licensed under the Apache License, Version 2.0 (the "License");
!! you may not use this file except in compliance with the License.
!!
!! Unless required by applicable law or agreed to in writing, software
!! distributed under the License is distributed on an "AS IS" BASIS,
!! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!! See the License for the specific language governing permissions and
!! limitations under the License.
!! @endlicenseblock
!!
!! @file

!> @ingroup OrchestrationMilhoja
!! @stubref{Orchestration_setupPipelineForCpuTasks}
!!
!! @brief Stub implementation of Orchestration_setupPipelineForCpuTasks
!!
!! @details
!! Set up the orchestration runtime so that it is ready to execute the given
!! task function with the CPU-only thread team configuration.
!! Upon successful completion of th setup, the orchestration runtime will
!! be ready to accept data items (tiles) pushed to it for execution
!! with Orchestration_pushTileToCpuPipeline calls.
!! To end the cycle, a call to Orchestration_setupPipelineForCpuTasks
!! has to be matched with an Orchestration_teardownPipelineForCpuTasks call
!! or a call of the generic Orchestration_teardownPipeline interface.
!!
!! @note
!! An actual, non-stub implementation of this interface is only available if
!! Flash-X is linked with a Milhoja library that was configured to support
!! wrapped tiles.
!!
!! @param MH_taskFunction       The task function to be executed by the single
!!                              thread team.  It is assumed that this function
!!                              was written to run kernels on CPUs.
!!                              Task functions generally are wrappers around
!!                              invocations of one or several user-provided
!!                              routines (such as "static Fortran routines"),
!!                              generated by CGKIT and available to callers of
!!                              the Orchestration interface by lines such as,
!!                              for example,
!!                                use cpu_tf_hydro_mod,ONLY: cpu_tf_hydro_Cpp2C
!!                              in the case of orchestrating a task for a
!!                              Hydro operation.
!! @param nThreads              The number of threads to activate in the team
!!                              that applies the task function to tiles.
subroutine Orchestration_setupPipelineForCpuTasks(MH_taskFunction, nThreads)
    use Orchestration_interfaceTypeDecl, ONLY : milhoja_runtime_taskFunction

    implicit none

    procedure(milhoja_runtime_taskFunction)            :: MH_taskFunction
    integer,                                intent(IN) :: nThreads

end subroutine Orchestration_setupPipelineForCpuTasks

