# Input file to set runtime parameters

[Logfile]
  run_comment = "Cross Flow problem"
  log_file = "INS_Cross_Flow.log"

[Grid]
  geometry = "cartesian"
  xmin = -10.0
  xmax = 30.0
  ymin = 0.0
  ymax = 20.0
  xl_boundary_type = "inflow_ins"
  xr_boundary_type = "outflow_ins"
  yl_boundary_type = "inflow_ins"
  yr_boundary_type = "slip_ins"
  gr_amrexMG_composite_solve = true
  gr_amrexMG_Tol = 1.0e-12
  gr_amrexMG_max_iter = 200
  nblockx = 20
  nblocky = 10
  nrefs = 10000000
  lrefine_min = 1
  lrefine_max = 1
  flux_correct = true
  enableMaskedGCFill = true

[IncompNS]
  ins_invReynolds = 0.0001
  ins_inflowVelScale = 2.0
  ins_gravY = -0.01
  ins_cflFlg = 1
  ins_cfl = 0.005
  ins_sigma = 0.005
  ins_dtSpec = 0.1e-4
  ins_pressureCorrect = false
  ins_intSchm = 2
  ins_advSchm = 2

[Outlet]
  out_buffer = 1.0

[Simulation]
  sim_lengthScaleMeters = 1.0
  sim_timeScaleSeconds = 1.0

[Multiphase]
  mph_rhoGas = 0.001
  mph_muGas = 0.02
  mph_iPropSmear = 1.5
  mph_invWeber = 0.004

[Driver]
  restart = false
  nend = 1200000
  tmax = 80
  dtinit = 0.1e-4
  tstep_change_factor = 1.01
  wall_clock_time_limit = 7000

[IO]
  basenm = "INS_Cross_Flow_"
  checkpointFileIntervalTime = 5.0
  plotFileIntervalTime = 1.0
  checkpointFileNumber = 0
  rolling_checkpoint = 2
  plotFileNumber = 0
  plot_var_1 = "pres"
  plot_var_2 = "velx"
  plot_var_3 = "vely"
  plot_var_4 = "dfun"
  plot_var_5 = "dust"
  ignoreForcedPlot = true
