#	Makefile for the FLASH code (equation of state module)

Eos = Eos_multiDim.o Eos.o Eos_init.o Eos_finalize.o Eos_guardCells.o Eos_getParameters.o Eos_interface.o Eos_getAbarZbar.o \
	Eos_sendOutputData.o Eos_vector.o Eos_fillEosData.o Eos_getFromEosData.o
