# Makefile for [source/Grid/GridMain]
Grid +=  Grid_getSingleCellVol.o \
	gr_initGeometry.o \
	Grid_renormAbundance.o Grid_limitAbundance.o Grid_renormMassScalars.o \
	gr_setDataStructInfo.o gr_findMean.o \
	gr_GCAllocScratch.o gr_GCScratchData.o gr_GCReleaseScratch.o \
	gr_GCTransferOneBlk.o \
	gr_tile2txtytz.o \
	gr_tilePolicyData.o
