MoL += ml_interface.o	\
	   ml_init.o		\
	   ml_finalize.o	\
		ml_initTableau.o	\
	   ml_advance.o		\
	   ml_calcRHS.o		\
	   ml_error.o		\
	   ml_warn.o		\
	   ml_status.o

MoL += ml_memInterface.o			\
	   ml_memAlloc.o 					\
	   ml_memFree.o				 	\
	   ml_memSetActiveRHS.o		 	\
	   ml_memReleaseActiveRHS.o	\
	   ml_memZero.o					\
	   ml_memCopy.o					\
	   ml_memAddToVars.o
