#	Makefile for unit Hydro/HydroMain/Spark
Hydro += Hydro_data.o \
	hy_rk_getFaceFlux.o hy_rk_interface.o \
	hy_rk_initSolnScratch.o \
	hy_rk_updateSoln.o \
	hy_rk_getGravAccel.o hy_rk_correctFluxes.o \
	hy_rk_shockDetect.o \
	hy_rk_getFlatteningLimiter.o \
	hy_rk_renormAbundance.o \
	hy_rk_saveFluxBuf.o

