Stencils += Stencils_interface.o \
            Stencils_init.o \
            Stencils_finalize.o

Stencils += Stencils_advectWeno2d.o \
            Stencils_advectWeno3d.o \
            Stencils_advectCentral2d.o \
            Stencils_advectCentral3d.o \
            Stencils_cnt_advectUpwind2d.o \
            Stencils_cnt_advectUpwind3d.o

Stencils += Stencils_diffusion2d.o \
            Stencils_diffusion3d.o

Stencils += Stencils_lsRedistance2d.o \
            Stencils_lsRedistance3d.o \
            Stencils_lsFaceProps2d.o \
            Stencils_lsFaceProps3d.o \
            Stencils_lsCenterProps.o \
            Stencils_lsNormals2d.o \
            Stencils_lsNormals3d.o \
            Stencils_lsCurvature2d.o \
            Stencils_lsCurvature3d.o

Stencils += Stencils_integrateEuler.o \
            Stencils_integrateAB2.o
