Multiphase += Multiphase_init.o \
              Multiphase_interface.o \
              Multiphase_advection.o \
              Multiphase_solve.o \
              Multiphase_redistance.o \
              Multiphase_indicators.o \
              Multiphase_finalize.o \
              Multiphase_setFluidProps.o \
              Multiphase_setThermalProps.o \
              Multiphase_setPressureJumps.o \
              Multiphase_getScalarProp.o \
              Multiphase_thermalForcing.o \
              Multiphase_velForcing.o \
              Multiphase_extrapFluxes.o \
              Multiphase_setMassFlux.o \
              Multiphase_divergence.o \
              Multiphase_reInitGridVars.o \
              Multiphase_getGridVar.o
