#	Makefile for unit RadTrans (API level)
RadTrans = RadTrans.o \
	   RadTrans_init.o \
	   RadTrans_interface.o \
	   RadTrans_getDbgContext.o \
	   RadTrans_planckInt.o \
	   RadTrans_mgdGetBound.o \
	   RadTrans_mgdSetBound.o \
	   RadTrans_computeDt.o \
	   RadTrans_mgdEFromT.o \
	   RadTrans_sumEnergy.o \
	   RadTrans_mgdSetEnergy.o \
	   RadTrans_mgdSetBc.o \
	   RadTrans_computeFluxLimiter.o \
	   RadTrans_prolongDgData.o \
	   RadTrans_prolongDgData_simple.o \
	   RadTrans_restrictDgData.o \
	   RadTrans_restrictDgData_simple.o \
	   RadTrans_finalize.o \
	   RadTrans_molExplicitRHS.o \
	   RadTrans_molImplicitRHS.o \
	   RadTrans_molFastRHS.o \
	   RadTrans_molImplicitUpdate.o \
	   RadTrans_molPostUpdate.o \
	   RadTrans_molPostFastUpdate.o \
	   RadTrans_molPreEvolve.o \
	   RadTrans_molPostTimeStep.o \
	   RadTrans_molPostRegrid.o
