
#	Makefile for the Helmholtz equation of state, species based

Eos += eos_helmConstData.o  eos_helmData.o\
       eos_readHfet.o eos_writeHfet.o \
       eos_helm.o  eos_helmSpecies.o eos_helmSpeciesInit.o




